// ===== 英语谜语 English Riddles（200题）=====
GameRegistry.register({
  id: 'enriddle',
  name: '英语谜语',
  icon: '💡',
  desc: '英语脑筋急转弯！小学到初中水平，练英语学推理！',
  difficulties: [
    { id: 'easy', name: '小学', icon: '🌱', desc: '简单英语谜语，基础词汇' },
    { id: 'medium', name: '初中基础', icon: '🔥', desc: '常见英语谜语，日常词汇' },
    { id: 'hard', name: '进阶挑战', icon: '💀', desc: '需要更多思考的英语谜语' },
  ],

  init(container, difficulty, onComplete) {
    const pool = EN_RIDDLES[difficulty];
    const total = 5;
    const shuffled = [...pool].sort(() => Math.random() - 0.5).slice(0, total);
    let index = 0, correct = 0;

    showQ();
    function showQ() {
      if (index >= total) { finish(); return; }
      const q = shuffled[index];
      container.innerHTML = `<div style="max-width:500px;width:100%;" class="animate-in">
        <div style="color:var(--text-dim);margin-bottom:12px;">第 ${index+1}/${total} 题 | ✅ ${correct}</div>
        <div style="font-size:1.2em;font-weight:600;margin-bottom:20px;line-height:1.7;background:var(--surface);padding:20px;border-radius:var(--radius);">💡 ${q.q}</div>
        <div class="flex-col" id="opts">${q.o.map((opt,i)=>`<button class="btn btn-secondary" data-idx="${i}" style="text-align:left;width:100%;">${String.fromCharCode(65+i)}. ${opt}</button>`).join('')}</div>
        <div id="fb" style="margin-top:10px;min-height:28px;font-weight:700;"></div></div>`;
      document.getElementById('opts').onclick=(e)=>{const b=e.target.closest('[data-idx]');if(!b)return;const c=+b.dataset.idx;const f=document.getElementById('fb');if(c===q.a){correct++;f.innerHTML='<div class="game-feedback success pop">✅ 正确！'+(q.j||'')+'</div>';}else{f.innerHTML='<div class="game-feedback info">❌ 正确答案：<b>'+q.o[q.a]+'</b>'+(q.j||'')+'</div>';}index++;setTimeout(showQ,1000);};
    }
    function finish(){
      const star=correct===5?'⭐⭐⭐⭐⭐':correct>=4?'⭐⭐⭐⭐':correct>=3?'⭐⭐⭐':'⭐';
      container.innerHTML=`<div class="result-card animate-in"><div class="result-icon">${correct>=4?'🎉':correct>=3?'👍':'📚'}</div><div class="result-title">${correct>=4?'谜语达人！':correct>=3?'还不错！':'继续努力！'}</div><div class="result-detail">${total}题答对<b style="color:var(--accent);">${correct}</b>题<br>${star}</div></div>`;
      setTimeout(()=>onComplete({win:correct>=3,score:total-correct,title:correct>=4?'太聪明了！':'挑战完成！',detail:`${total}题答对${correct}题`}),1500);
    }
  }
});

// ===== 英语谜语题库 =====
const EN_RIDDLES = {
  easy: [
    {q:'What has hands but can\'t clap?',o:['A clock','A person','A dog','A tree'],a:0,j:' 😂 A clock has hands!'},
    {q:'What has a face but can\'t see?',o:['A person','A clock','A mirror','A book'],a:1},
    {q:'What gets wetter the more it dries?',o:['A towel','A cloth','A mop','A shirt'],a:0},
    {q:'What has legs but doesn\'t walk?',o:['A bird','A table/chair','A car','A fish'],a:1},
    {q:'What can you break without touching it?',o:['A window','A promise','A bone','A plate'],a:1},
    {q:'What has a neck but no head?',o:['A bottle','A person','A giraffe','A snake'],a:0},
    {q:'What can you catch but not throw?',o:['A ball','A cold','A fish','A toy'],a:1},
    {q:'What goes up but never comes down?',o:['A balloon','Your age','A bird','Smoke'],a:1},
    {q:'What is full of holes but still holds water?',o:['A bucket','A sponge','A net','A basket'],a:1},
    {q:'What has an eye but cannot see?',o:['A needle','A person','An animal','A camera'],a:0},
    {q:'What has teeth but cannot eat?',o:['A baby','A comb','A dog','A tiger'],a:1},
    {q:'I have a tail and a head, but no body. What am I?',o:['A snake','A coin','A fish','A bird'],a:1},
    {q:'What can travel around the world while staying in a corner?',o:['A plane','A stamp','An email','A thought'],a:1},
    {q:'What has words but never speaks?',o:['A person','A book','A phone','A TV'],a:1},
    {q:'What has a bed but never sleeps?',o:['A hotel','A river','A chair','A person'],a:1},
    {q:'What gets bigger the more you take from it?',o:['A balloon','A hole','A bank account','A bag'],a:1},
    {q:'What can you see once in a minute, twice in a moment, but never in a thousand years?',o:['The sun','The letter M','The moon','The stars'],a:1},
    {q:'What is always in front of you but cannot be seen?',o:['The past','The future','Air','Your nose'],a:1},
    {q:'What month of the year has 28 days?',o:['February','All of them','January','None'],a:1},
    {q:'What has four wheels and flies?',o:['An airplane','A garbage truck','A car','A helicopter'],a:1,j:' 😂 A garbage truck!'},
    {q:'I am white when dirty, black when clean. What am I?',o:['A shirt','A blackboard','Paper','Snow'],a:1},
    {q:'What kind of room has no windows or doors?',o:['A bedroom','A mushroom','A classroom','A bathroom'],a:1},
    {q:'What begins with T, ends with T, and has T in it?',o:['A teapot','A tent','A test','A tablet'],a:0},
    {q:'What can you keep after giving to someone?',o:['Money','Your word/promise','A gift','Time'],a:1},
    {q:'I have cities but no houses, forests but no trees, water but no fish. What am I?',o:['A dream','A map','A painting','A photo'],a:1},
    {q:'What invention lets you look right through a wall?',o:['X-ray glasses','A window','A door','A camera'],a:1},
    {q:'The more you take, the more you leave behind. What are they?',o:['Memories','Footsteps','Money','Time'],a:1},
    {q:'What has a ring but no finger?',o:['A telephone','A jewelry box','A door','A tree'],a:0},
    {q:'What has ears but cannot hear?',o:['A person','A corn field','A dog','A radio'],a:1},
    {q:'If you drop me, I will crack. If you smile at me, I will smile back. What am I?',o:['A mirror','An egg','Glass','A friend'],a:0},
    {q:'What is black when you buy it, red when you use it, and gray when you throw it away?',o:['Charcoal','Paint','Ink','Wood'],a:0},
    {q:'What has a head and a tail but no body?',o:['A snake','A coin','A fish','A comet'],a:1},
    {q:'What five-letter word becomes shorter when you add two letters to it?',o:['Short','Small','Tiny','Brief'],a:0,j:' 😂 short + er = shorter!'},
    {q:'I am tall when young, short when old. What am I?',o:['A tree','A candle','A person','A building'],a:1},
    {q:'What comes down but never goes up?',o:['Rain','Your age','The sun','A bird'],a:0},
    {q:'What begins with E, ends with E, and has one letter?',o:['Eye','Envelope','Elephant','Eagle'],a:1,j:' 😂 An envelope has one letter inside!'},
    {q:'What is as light as a feather, yet the strongest person can\'t hold it for five minutes?',o:['Breath/air','A feather','A balloon','A thought'],a:0},
    {q:'I have lakes with no water, mountains with no stone, cities with no buildings. What am I?',o:['A map','A dream','A painting','A story'],a:0},
    {q:'What word is always spelled wrong?',o:['Wrong','Misspelled','Incorrect','Error'],a:0,j:' 😂 The word "wrong" is always spelled w-r-o-n-g!'},
    {q:'What kind of tree can you carry in your hand?',o:['A palm tree','A bonsai','A seed','A stick'],a:0},
    {q:'What has 13 hearts but no other organs?',o:['A deck of cards','A clock','A puzzle','An alien'],a:0},
    {q:'What can fill a room but takes up no space?',o:['Light','Water','Air','Sound'],a:0},
    {q:'What is the end of everything?',o:['Death','The letter G','Nothing','Space'],a:1,j:' 😂 everythinG ends with G!'},
    {q:'What has one eye but cannot see?',o:['A needle','A cyclops','A potato','A camera'],a:0},
    {q:'What tastes better than it smells?',o:['A tongue','Cheese','Fruit','Candy'],a:0,j:' 😂 Your tongue!'},
    {q:'What has hands but can\'t write?',o:['A clock','A baby','A statue','A robot'],a:0},
    {q:'What do you call a bear with no teeth?',o:['A gummy bear','Toothless','A cub','Soft bear'],a:0},
    {q:'What kind of band never plays music?',o:['A rubber band','A rock band','A jazz band','A marching band'],a:0},
    {q:'What is always coming but never arrives?',o:['Tomorrow','The sun','A train','A letter'],a:0},
    {q:'What has a bottom at the top?',o:['Your legs','A hill','A bottle','A mountain'],a:0,j:' 😂 Your legs!'},
    {q:'What can you hear but not touch or see?',o:['Your voice/echo','Music','A ghost','Wind'],a:0},
    {q:'What goes through towns and over hills but never moves?',o:['A road','A river','Wind','Clouds'],a:0},
    {q:'What is at the end of a rainbow?',o:['Gold','The letter W','A pot','Nothing'],a:1,j:' 😂 rainboW ends with W!'},
    {q:'What loses its head in the morning and gets it back at night?',o:['A pillow','The sun','A chicken','A clock'],a:0},
    {q:'What can you put in a bucket to make it lighter?',o:['A hole','Water','Air','Sand'],a:0},
    {q:'What is the richest nut?',o:['A cash-ew','Walnut','Almond','Peanut'],a:0,j:' 😂 Cash-ew sounds like cashew!'},
    {q:'What question can you never answer "yes" to?',o:['Are you asleep?','Are you hungry?','Are you happy?','Are you tall?'],a:0},
    {q:'What two things can you never eat for breakfast?',o:['Lunch and dinner','Pizza and ice cream','Cereal and milk','Eggs and bacon'],a:0},
    {q:'What is brown and sticky?',o:['A stick','Mud','Chocolate','Glue'],a:0,j:' 😂 A stick!'},
    {q:'What can run but never walks?',o:['Water','A car','A computer program','A clock'],a:0},
    {q:'What kind of key can\'t open a door?',o:['A monkey','A piano key','A donkey','All of them'],a:3,j:' 😂 Monkey, donkey, and piano key!'},
    {q:'Where does Friday come before Thursday?',o:['In the dictionary','In a time machine','Never','In a dream'],a:0,j:' 😂 F comes before T in the alphabet!'},
    {q:'Why did the kid bring a ladder to school?',o:['To go to high school','For gym class','To fix the roof','To get a book'],a:0},
    {q:'What animal can jump higher than a house?',o:['A kangaroo','All animals - houses can\'t jump','A flea','A cat'],a:1},
    {q:'I have keys but no locks. I have space but no room. What am I?',o:['A keyboard','A map','A library','A phone'],a:0},
    {q:'What belongs to you but others use it more than you do?',o:['Your name','Your phone','Your house','Your car'],a:0},
    {q:'What do you call a fish with no eye?',o:['Fsh','Blind fish','Cyclops fish','Nemo'],a:0,j:' 😂 Fsh — no "i"!'},
  ],

  medium: [
    {q:'I speak without a mouth and hear without ears. I have no body but come alive with wind. What am I?',o:['An echo','A ghost','Music','A bird'],a:0},
    {q:'The more of me you have, the less you see. What am I?',o:['Darkness','Money','Friends','Books'],a:0},
    {q:'What disappears as soon as you say its name?',o:['Silence','Magic','A secret','An echo'],a:0},
    {q:'I am not alive, but I grow. I don\'t have lungs but I need air. What am I?',o:['Fire','A plant','A balloon','Water'],a:0},
    {q:'You see me once in June, twice in November, but not at all in May. What am I?',o:['The sun','The letter E','The moon','Rain'],a:1},
    {q:'What can you hold in your left hand but not in your right hand?',o:['Your right elbow','A pen','Water','Nothing'],a:0},
    {q:'What word contains 26 letters but only three syllables?',o:['Alphabet','Dictionary','Encyclopedia','Sentence'],a:0},
    {q:'I follow you all the time and copy your every move, but you can\'t touch me or catch me. What am I?',o:['Your shadow','A ghost','Your memory','Your reflection'],a:0},
    {q:'What has many keys but can\'t open a single lock?',o:['A piano/keyboard','A keychain','A map','A code'],a:0},
    {q:'What English word has three consecutive double letters?',o:['Bookkeeper','Mississippi','Balloon','Coffee'],a:0,j:' 😂 Bookkeeper has oo, kk, ee!'},
    {q:'I make two people out of one. What am I?',o:['A mirror','A friend','Love','A door'],a:0},
    {q:'What starts with P, ends with E, and has thousands of letters?',o:['Post Office','People','Poem','Page'],a:0,j:' 😂 Post Office has thousands of letters/邮件!'},
    {q:'The person who makes it, sells it. The person who buys it never uses it. The person who uses it never knows they\'re using it. What is it?',o:['A coffin','Medicine','A gift','A secret'],a:0},
    {q:'What is easy to get into but hard to get out of?',o:['Trouble','A pool','A car','A house'],a:0},
    {q:'Born at the same time as the world, I will be with you until death. What am I?',o:['Your soul','Your name','Your shadow','Air'],a:2},
    {q:'What can be cracked, made, told, and played?',o:['A joke','An egg','A code','A record'],a:0},
    {q:'What is seen in the middle of March and April that can\'t be seen at the beginning or end of either month?',o:['The sun','The letter R','Spring','Rain'],a:1},
    {q:'I am an odd number. Take away a letter and I become even. What number am I?',o:['Seven','Eleven','Nine','Five'],a:0,j:' 😂 Seven minus S = even!'},
    {q:'What goes up and down but never moves?',o:['Temperature','A staircase','An elevator','The sun'],a:0},
    {q:'What building has the most stories?',o:['A library','A skyscraper','A school','A hotel'],a:0},
    {q:'Before Mount Everest was discovered, what was the highest mountain in the world?',o:['Mount Everest','K2','Kangchenjunga','Unknown'],a:0,j:' 😂 It was still Everest — just undiscovered!'},
    {q:'What is so fragile that saying its name breaks it?',o:['Silence','Glass','A secret','A bubble'],a:0},
    {q:'What can you serve but never eat?',o:['A tennis ball/volleyball','A meal','A cake','Water'],a:0},
    {q:'What has 88 keys but cannot open a single door?',o:['A piano','A computer','A calculator','A phone'],a:0},
    {q:'What is the center of gravity?',o:['The letter V','The Earth\'s core','The Sun','Space'],a:0,j:' 😂 graVity!'},
    {q:'I am taken from a mine and shut up in a wooden case, from which I am never released. What am I?',o:['Pencil lead/graphite','Gold','Diamond','Coal'],a:0},
    {q:'What word is pronounced the same if you remove four of its five letters?',o:['Queue','Table','House','Water'],a:0,j:' 😂 Queue → just Q!'},
    {q:'What is the longest word in the English language?',o:['Smiles','Pneumonoultramicroscopicsilicovolcanoconiosis','Supercalifragilisticexpialidocious','Antidisestablishmentarianism'],a:0,j:' 😂 Smiles — there\'s a mile between the S\'s!'},
    {q:'What has hundreds of ears but can\'t hear a thing?',o:['A cornfield','A library','A concert hall','A radio'],a:0},
    {q:'What word looks the same upside down and backward?',o:['SWIMS','NOON','RACECAR','BOB'],a:0,j:' 😂 SWIMS!'},
    {q:'What can you make that no one — not even you — can see?',o:['Noise/sound','A shadow','A dream','A memory'],a:0},
    {q:'What occurs once in a minute, twice in a moment, but never in a hundred years?',o:['The letter M','An opportunity','A miracle','A coincidence'],a:0},
    {q:'I am something people love or hate. I change people\'s appearances and thoughts. What am I?',o:['Age/time','Money','Education','Food'],a:0},
    {q:'What do you break before you use it?',o:['An egg','A promise','A seal','A code'],a:0},
    {q:'I have no life but I can die. What am I?',o:['A battery','A story','A plant','Water'],a:0},
    {q:'What has a head but never weeps, has a bed but never sleeps?',o:['A river','A person','A cat','A clock'],a:0},
    {q:'What do you buy to eat but never consume?',o:['A plate/bowl','A ticket','A gift card','A utensil'],a:0},
    {q:'What comes once in a year, twice in a week, but never in a day?',o:['The letter E','Christmas','Weekend','New Year'],a:0},
    {q:'Feed me and I live, give me a drink and I die. What am I?',o:['Fire','A plant','A pet','A computer'],a:0},
    {q:'What kind of coat can only be put on when wet?',o:['A coat of paint','A raincoat','A winter coat','A lab coat'],a:0},
    {q:'What do you throw out when you want to use it, and take in when you don\'t?',o:['An anchor','A fishing line','Trash','A net'],a:0},
    {q:'I am full of keys but cannot open any door. What am I?',o:['A piano','A dictionary','A keyboard','A map'],a:0},
    {q:'What can point in every direction but cannot reach its destination?',o:['A compass','Your finger','A sign','A map'],a:0,j:' 😂 A compass — it points but never arrives!'},
    {q:'What passes before the sun but makes no shadow?',o:['The wind','A cloud','A bird','Time'],a:0},
    {q:'What kind of cup cannot hold water?',o:['A hiccup','A paper cup','A broken cup','A trophy cup'],a:0,j:' 😂 A hiccup!'},
    {q:'What can run but cannot walk, has a mouth but cannot talk?',o:['A river','A person','A dog','A car'],a:0},
    {q:'What has a face and two hands but no arms or legs?',o:['A clock','A person','A statue','A doll'],a:0},
    {q:'What can you find in a cupboard that can never be put in a cupboard?',o:['The word "a"','Food','Clothes','Dishes'],a:0,j:' 😂 "A cupboard" contains the word "a"!'},
    {q:'I am a word. If you add a letter, I become shorter. What am I?',o:['Short','Word','Small','Tiny'],a:0},
    {q:'What do you call a snowman with a six-pack?',o:['An abdominal snowman','A fit snowman','Abs-man','Snow-bodybuilder'],a:0,j:' 😂 An abdominal snowman (abominable snowman)!'},
    {q:'What runs all around a backyard yet never moves?',o:['A fence','A dog','A child','Grass'],a:0},
    {q:'What falls but never gets hurt?',o:['Rain/snow','A baby','A leaf','An apple'],a:0},
    {q:'I give you a group of three. One is sitting down, and will never get up. The second eats as much as is given to him, yet is always hungry. The third goes away and never returns. What are they?',o:['Stove, fire, smoke','Cat, dog, bird','Tree, river, wind','Sun, moon, stars'],a:0},
    {q:'A cowboy rode into town on Friday. He stayed three days and rode out on Friday. How is this possible?',o:['His horse is named Friday','Time travel','He lied','It was Saturday'],a:0},
    {q:'I am a word of letters three; add two and fewer there will be. What am I?',o:['Few','One','Two','The'],a:0,j:' 😂 Few + er = fewer!'},
    {q:'What can fill a room but takes up no space?',o:['Light','Water','Air','Sound'],a:0},
    {q:'What goes up when rain comes down?',o:['An umbrella','Water level','Mud','Grass'],a:0},
    {q:'What is the difference between a jeweler and a jailer?',o:['One sells watches, one watches cells','They are the same','One works days, one nights','Nothing'],a:0},
    {q:'What has four fingers and a thumb but is not alive?',o:['A glove','A statue','A robot hand','A drawing'],a:0},
    {q:'What grows up while growing down?',o:['A plant/root','A stalactite','A person aging','A mountain'],a:0},
    {q:'What is easy to get but hard to keep?',o:['A promise/trust','Money','Friends','Knowledge'],a:0},
    {q:'What has no beginning, end, or middle?',o:['A circle/doughnut','A line','A point','Space'],a:0,j:' 😂 A doughnut has a hole in the middle!'},
    {q:'In what month do people talk the least?',o:['February','December','January','November'],a:0,j:' 😂 February has the fewest days!'},
    {q:'What can\'t be used until it\'s broken?',o:['An egg','A promise','A seal','A lock'],a:0},
    {q:'The more there is, the less you see. What is it?',o:['Darkness/fog','Light','Water','People'],a:0},
    {q:'What kind of dog never bites?',o:['A hot dog','A stuffed dog','A police dog','A dead dog'],a:0},
    {q:'What word starts with "e", ends with "e", and has one letter?',o:['Envelope','Eye','Elephant','Eagle'],a:0,j:' 😂 An envelope has one letter inside!'},
  ],

  hard: [
    {q:'I turn polar bears white and I will make you cry. I make guys have to pee and girls comb their hair. I make celebrities look stupid and normal people look like celebrities. What am I?',o:['The answer is "No"','Onions','Time','Mirrors'],a:0,j:' 😂 Say "No" to each line — no, polar bears aren\'t white (they have black skin)...'},
    {q:'What 7-letter word becomes longer when you remove the third letter?',o:['Lounger','Longest','Smaller','Tiniest'],a:0,j:' 😂 Lounger → longer!'},
    {q:'A man is looking at a photograph. Someone asks him, "Who is in the picture?" He replies, "Brothers and sisters I have none, but that man\'s father is my father\'s son." Who is in the picture?',o:['His son','Himself','His father','His nephew'],a:0},
    {q:'What word in the English language uses all five vowels in order?',o:['Facetious','Beautiful','Education','Audience'],a:0,j:' 😂 Facetious has a-e-i-o-u in order!'},
    {q:'Paul\'s height is six feet, he\'s an assistant at a butcher\'s shop, and wears size 9 shoes. What does he weigh?',o:['Meat','180 pounds','80 kilograms','Nobody knows'],a:0,j:' 😂 He\'s a butcher — he weighs meat!'},
    {q:'What can you add to a room to make it brighter?',o:['Windows','Lamps','A window','Paint'],a:2,j:' 😂 Add "a" — room → a room!'},
    {q:'I am not alive, but I have 5 fingers. What am I?',o:['A glove','A hand statue','A clock','A shadow'],a:0},
    {q:'The 22nd and 24th presidents of the United States had the same mother and father, but were not brothers. How?',o:['Same person (Grover Cleveland)','Step-brothers','Adopted','Twins separated'],a:0,j:' 😂 Grover Cleveland served non-consecutive terms!'},
    {q:'What common English word will describe a person or thing as not being found in any place, and yet with one small change, will describe a room in a house?',o:['Nowhere → Now here','Absent','Missing','Lost'],a:0},
    {q:'I have a tongue but cannot talk. I have no legs but sometimes walk. What am I?',o:['A shoe','A snake','A river','A clock'],a:0},
    {q:'You measure my life in hours and I serve you by dying. I\'m quick when I\'m thin and slow when I\'m fat. What am I?',o:['A candle','A clock','A battery','A person'],a:0},
    {q:'What is the only English word that has a silent letter for every single letter in its name?',o:['Queue','Knight','Psychology','Pneumonia'],a:0,j:' 😂 Queue — pronounced just "Q"!'},
    {q:'What word has five consecutive vowels?',o:['Queueing','Beautiful','Audacious','Education'],a:0,j:' 😂 Queueing has u-e-u-e-i — five vowels in a row!'},
    {q:'A girl has as many brothers as sisters, but each brother has only half as many brothers as sisters. How many brothers and sisters?',o:['4 sisters, 3 brothers','3 sisters, 2 brothers','5 sisters, 4 brothers','2 sisters, 1 brother'],a:0},
    {q:'What is unusual about the following words: revive, banana, grammar, voodoo, assess, potato, dresser, uneven?',o:['Palindromes when first letter moved to end','All have double letters','All are fruits','Nothing special'],a:0},
    {q:'What makes a man bald-headed?',o:['Lack of hair','Age','Stress','Genetics'],a:0,j:' 😂 The word "bald" — man → bald man. Think about it...'},
    {q:'What five-letter word has one left when two are removed?',o:['Stone','Three','Seven','Alone'],a:0,j:' 😂 Stone → one (remove st)!'},
    {q:'A clerk at a butcher shop stands five feet ten inches tall and wears size 13 sneakers. What does he weigh?',o:['Meat','200 pounds','85 kilograms','Size 13'],a:0},
    {q:'What is always in bed but never sleeps?',o:['A river','A person','A cat','A clock'],a:0},
    {q:'What word, when written in capital letters, is the same forwards, backwards, and upside down?',o:['NOON','SWIMS','MOM','WOW'],a:0},
    {q:'What can go up a chimney down, but can\'t go down a chimney up?',o:['An umbrella','Smoke','Santa','A bird'],a:0},
    {q:'I have seven rings made of rock and ice. You cannot wear them on your fingers; they are not easy to find. What am I?',o:['Saturn','A jewelry store','A tree trunk','Jupiter'],a:0},
    {q:'What starts with "e", ends with "e", and contains one letter that is not "e"?',o:['Envelope','Everywhere','Experience','Elsewhere'],a:0,j:' 😂 Envelope — has one letter (mail) inside!'},
    {q:'I am a word that begins with the letter "i". If you add the letter "a" to me, I become a new word with a different meaning, yet sound exactly the same. What word am I?',o:['Isle → aisle','Ice','Iron','Itch'],a:0},
    {q:'What is at the beginning of eternity, the end of time and space, the beginning of every end, and the end of every race?',o:['The letter E','God','Nothing','Death'],a:0},
    {q:'The person who invented it doesn\'t want it. The person who bought it doesn\'t need it. The person who needs it doesn\'t know it. What is it?',o:['A coffin','A medicine','A secret','A weapon'],a:0},
    {q:'What kind of lion never roars?',o:['A dandelion','A dead lion','A statue','A cowardly lion'],a:0,j:' 😂 A dandeLION!'},
    {q:'What word is always pronounced wrong?',o:['Wrong','Misspelled','Incorrectly','Mistake'],a:0},
    {q:'How can you lift an elephant with one hand?',o:['You can\'t','It\'s not a problem if it\'s a toy elephant','With a crane','Use two hands'],a:1},
    {q:'What has 21 eyes but cannot see?',o:['A die/dice','A potato','A spider','A deck of cards'],a:0,j:' 😂 A die: 1+2+3+4+5+6 = 21 dots/eyes!'},
    {q:'You are driving a bus. At the first stop, 3 people get on. At the second stop, 5 more get on and 2 get off. At the third stop, 1 gets off and 4 get on. What color are the bus driver\'s eyes?',o:['Whatever color your eyes are','Brown','Blue','Don\'t know'],a:0,j:' 😂 YOU are the bus driver!'},
    {q:'What is 3/7 chicken, 2/3 cat, and 2/4 goat?',o:['Chicago','Chicken','Cat goat','Animal'],a:0,j:' 😂 CHIcken + caT + goAT = Chicago!'},
    {q:'What\'s full of information but can\'t think?',o:['A book/encyclopedia','A computer','A library','The Internet'],a:0},
    {q:'If two\'s company and three\'s a crowd, what are four and five?',o:['Nine','A party','Too many','A group'],a:0,j:' 😂 4 + 5 = 9!'},
    {q:'What 8-letter word can have consecutive letters taken away one by one and still remain a word until only one letter remains?',o:['Starting','Anything','Suddenly','Together'],a:0,j:' 😂 Starting → staring → string → sting → sing → sin → in → I!'},
    {q:'Which weighs more: a ton of feathers or a ton of bricks?',o:['Neither — both weigh a ton','Bricks','Feathers','Depends on the feather type'],a:0},
    {q:'What word contains all 26 letters?',o:['Alphabet','Dictionary','Encyclopedia','All of the above'],a:0,j:' 😂 Alphabet contains all the letters... of the word "alphabet"!'},
    {q:'I\'m where yesterday follows today, and tomorrow is in the middle. What am I?',o:['A dictionary','A calendar','A dream','A time machine'],a:0,j:' 😂 In the dictionary: yesterday comes after today alphabetically!'},
    {q:'What occurs twice in a week, once in a year, but never in a day?',o:['The letter E','Monday','Weekend','Holiday'],a:0},
    {q:'What has roots nobody sees, is taller than trees, up up it goes, yet never grows?',o:['A mountain','A building','A flagpole','The sun'],a:0},
    {q:'A box without hinges, key, or lid, yet golden treasure inside is hid. What is it?',o:['An egg','A treasure chest','A safe','A nut'],a:0},
    {q:'This thing all things devours: birds, beasts, trees, flowers; gnaws iron, bites steel; grinds hard stones to meal. What is it?',o:['Time','Water','Fire','Wind'],a:0},
    {q:'Thirty white horses on a red hill, first they champ, then they stamp, then they stand still. What are they?',o:['Teeth','Sheep','Clouds','Waves'],a:0},
    {q:'Voiceless it cries, wingless flutters, toothless bites, mouthless mutters. What is it?',o:['The wind','A ghost','An echo','Silence'],a:0},
    {q:'An eye in a blue face saw an eye in a green face. "That eye is like this eye," said the first eye. What is it?',o:['Sun on a flower/field','Mirror','Window','Camera'],a:0,j:' 😂 The sun looking at its reflection in a field!'},
    {q:'It cannot be seen, cannot be felt, cannot be heard, cannot be smelt. It lies behind stars and under hills, and empty holes it fills. What is it?',o:['Darkness','Air','Silence','Time'],a:0},
    {q:'Alive without breath, as cold as death; never thirsty, ever drinking, all in mail never clinking. What is it?',o:['A fish','A statue','Ice','A robot'],a:0},
    {q:'What has no hinges, key, or lid, but inside golden treasure is hid?',o:['An egg','A treasure map','A book','A brain'],a:0},
    {q:'This is a most unusual paragraph. How quickly can you find out what is so unusual about it?',o:['No letter E','All words start with T','It\'s a palindrome','No vowels'],a:0,j:' 😂 The entire paragraph has no letter E!'},
    {q:'What\'s black and white and red all over?',o:['A newspaper','A zebra with sunburn','A penguin in paint','A checkerboard'],a:0,j:' 😂 Red = read! A newspaper is read all over!'},
    {q:'What can travel around the world while staying in a corner?',o:['A stamp','The Internet','A satellite','A thought'],a:0},
    {q:'What is the longest word in the dictionary?',o:['Smiles','Pneumonoultramicro...','Antidisestablishment...','Supercalifragilistic...'],a:0,j:' 😂 Smiles — there\'s a MILE between the S\'s!'},
    {q:'I am the beginning of everything, the end of everywhere. I\'m the beginning of eternity, the end of time and space. What am I?',o:['The letter E','God','Nothing','Space'],a:0},
    {q:'What is so delicate that saying its name breaks it?',o:['Silence','Glass','A bubble','A secret'],a:0},
    {q:'What has teeth but cannot bite?',o:['A comb','A baby','A doll','Scissors'],a:0},
    {q:'What goes up and never comes down?',o:['Your age','Smoke','A balloon','A rocket'],a:0},
    {q:'How many letters are in "the alphabet"?',o:['11','26','8','The answer is in the question'],a:0,j:' 😂 Count: t-h-e-a-l-p-h-a-b-e-t = 11 letters!'},
    {q:'What begins with T, finishes with T, and has T in it?',o:['A teapot','A test','A tent','A tablet'],a:0},
    {q:'What is at the end of everything?',o:['The letter G','Death','Space','Nothing'],a:0},
    {q:'I am not alive, but I grow; I don\'t have lungs, but I need air; I don\'t have a mouth, but water kills me. What am I?',o:['Fire','A plant','A virus','A battery'],a:0},
    {q:'The man who made it doesn\'t want it. The man who bought it doesn\'t need it. The man who needs it doesn\'t know it. What is it?',o:['A coffin','A weapon','Medicine','A gift'],a:0},
    {q:'A man pushes his car to a hotel and tells the owner he\'s bankrupt. Why?',o:['Playing Monopoly','He lost his job','His business failed','Car broke down'],a:0},
    {q:'What gets sharper the more you use it?',o:['Your brain/mind','A knife','A pencil','Scissors'],a:0},
    {q:'What has branches but no fruit, trunk, or leaves?',o:['A bank','A river','A tree stump','A government'],a:0},
    {q:'What can\'t talk but will reply when spoken to?',o:['An echo','A mirror','A radio','A phone'],a:0},
    {q:'What is made of water but if you put it into water it will die?',o:['An ice cube','A fish','A boat','Salt'],a:0},
  ],
};
